---
version: '3.8'
services:

  # Container that will execute a supervisor with 4 child processes:
  # shibauthorizer, shibresponder, and shibd (which together will act as a SAML
  # SP) and an NGINX, that will use Shibboleth to secure certain locations,
  # proxy the edusign backen app at the www container, and serve the js bundles
  # from the jsbuild volume.

  sp:
    image: docker.sunet.se/edusign-sp:latest
    expose:
      - 80
      - 443
    networks:
      edusign:
        ipv4_address: 172.20.10.201
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - SP_HOSTNAME
      - DISCO_URL
      - METADATA_FILE

  # Container that will execute a gunicorn process driving the edusign backen
  # app.

  www:
    image: docker.sunet.se/edusign-app:latest
    networks:
      edusign:
        ipv4_address: 172.20.10.202
    expose:
      - 8080
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - "PYTHONPATH=/opt/edusign/edusign-webapp/src"
      - SERVER_NAME
      - SECRET_KEY
      - EDUSIGN_API_BASE_URL
      - EDUSIGN_API_PROFILE
      - EDUSIGN_API_USERNAME
      - EDUSIGN_API_PASSOWRD
      - SIGNER_ATTRIBUTES
    depends_on:
      - sp

volumes:

  # Volume to hold all the interesting logs

  edusignlogs:
    name: edusignlogs

networks:
  edusign:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24

