---
version: '3.8'
services:

  # Container that will execute a supervisor with 4 child processes:
  # shibauthorizer, shibresponder, and shibd (which together will act as a SAML
  # SP) and an NGINX, that will use Shibboleth to secure certain locations,
  # proxy the edusign backen app at the www container, and serve the js bundles
  # from the jsbuild volume.

  sp:
    image: docker.sunet.se/edusign-sp:latest
    expose:
      - 80
      - 443
    networks:
      edusign:
        ipv4_address: 172.20.10.201
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - "SP_HOSTNAME=sp.edusign.docker"
      - "DISCO_URL=https://md.nordu.net/role/idp.ds"
      - "MAX_FILE_SIZE=20M"
      - "EDUSIGN_APP_VERSION=v0.1.1"
      - METADATA_FILE
    depends_on:
      - www

  # Container that will execute a gunicorn process driving the edusign backen
  # app.

  www:
    image: docker.sunet.se/edusign-app:latest
    networks:
      edusign:
        ipv4_address: 172.20.10.202
    expose:
      - 8080
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - "SP_HOSTNAME=sp.edusign.docker"
      - "SECRET_KEY=supersecret"
      - "EDUSIGN_API_BASE_URL=https://sig.idsec.se/signint/v1/"
      - "EDUSIGN_API_PROFILE=edusign-test"
      - "EDUSIGN_API_USERNAME=dummy"
      - "EDUSIGN_API_PASSWORD=dummy"
      - "SIGN_REQUESTER_ID=https://sig.idsec.se/shibboleth"
      - "SIGNER_ATTRIBUTES=urn:oid:2.5.4.42,givenName;urn:oid:2.5.4.4,sn;urn:oid:0.9.2342.19200300.100.1.3,mail;urn:oid:2.16.840.1.113730.3.1.241,displayName"
      - "EDUSIGN_APP_VERSION=v0.1.1"

volumes:

  # Volume to hold all the interesting logs

  edusignlogs:
    name: edusignlogs

networks:
  edusign:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24

