---
version: '3.8'
services:

  # Container that will execute a supervisor with 4 child processes:
  # shibauthorizer, shibresponder, and shibd (which together will act as a SAML
  # SP) and an NGINX, that will use Shibboleth to secure certain locations,
  # proxy the edusign backen app at the www container, and serve the js bundles
  # from the jsbuild volume.

  sp:
    image: docker.sunet.se/edusign-sp:latest
    expose:
      - 80
      - 443
    networks:
      edusign:
        ipv4_address: 172.20.10.201
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - SP_HOSTNAME
      - DISCO_URL
      - MAX_FILE_SIZE
      - METADATA_FILE
    depends_on:
      - www

  # Container that will execute a gunicorn process driving the edusign backen
  # app.

  www:
    image: docker.sunet.se/edusign-app:latest
    networks:
      edusign:
        ipv4_address: 172.20.10.202
    expose:
      - 8080
    volumes:
      - edusignlogs:/var/log/edusign:rw
    environment:
      - SP_HOSTNAME
      - SECRET_KEY
      - EDUSIGN_API_BASE_URL
      - EDUSIGN_API_PROFILE
      - EDUSIGN_API_USERNAME
      - EDUSIGN_API_PASSWORD
      - MULTISIGN_BUTTONS
      - SIGN_REQUESTER_ID
      - SIGNER_ATTRIBUTES
      - SCOPE_WHITELIST
      - STORAGE_CLASS_PATH
      - LOCAL_STORAGE_BASE_DIR
      - AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION_NAME
      - AWS_BUCKET_NAME
      - DOC_METADATA_CLASS_PATH
      - SQLITE_MD_DB_PATH
      - REDIS_URL
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_DEFAULT_SENDER
      - MAIL_USE_TLS
      - MAIL_USE_SSL
      - MAIL_DEBUG
      - MAIL_SUPPRESS_SEND
      - MAIL_ASCII_ATTACHMENTS

volumes:

  # Volume to hold all the interesting logs

  edusignlogs:
    name: edusignlogs

networks:
  edusign:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24

