[version]
current = "1.1.2b5"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  ((rc|b)
  (?P<release_candidate>\d+))?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "backend/Dockerfile"
search = 'ENV EDUSIGN_APP_VERSION v{current_version}'

[[file]]
src = "nginx/Dockerfile"
search = 'ENV EDUSIGN_APP_VERSION v{current_version}'

[[file]]
src = "Makefile"
search = 'VERSION={current_version}'
